// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZexjugo3slfC_OMpCPEh1iGAwJlhpDts',
    appId: '1:959517909012:web:cc4f725a7cc937ed8d8701',
    messagingSenderId: '959517909012',
    projectId: 'flora-d6444',
    authDomain: 'flora-d6444.firebaseapp.com',
    storageBucket: 'flora-d6444.firebasestorage.app',
    measurementId: 'G-PDMVYLNHBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvihDPcJADWwquo0zn1qraiisL-FFEyWk',
    appId: '1:959517909012:android:4d1ea237f2c5beb48d8701',
    messagingSenderId: '959517909012',
    projectId: 'flora-d6444',
    storageBucket: 'flora-d6444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlXguvDP7Qe2dwmcWdWlZHHDmbvibxoYM',
    appId: '1:959517909012:ios:89e651c25d205c158d8701',
    messagingSenderId: '959517909012',
    projectId: 'flora-d6444',
    storageBucket: 'flora-d6444.firebasestorage.app',
    iosBundleId: 'com.example.flora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlXguvDP7Qe2dwmcWdWlZHHDmbvibxoYM',
    appId: '1:959517909012:ios:89e651c25d205c158d8701',
    messagingSenderId: '959517909012',
    projectId: 'flora-d6444',
    storageBucket: 'flora-d6444.firebasestorage.app',
    iosBundleId: 'com.example.flora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZexjugo3slfC_OMpCPEh1iGAwJlhpDts',
    appId: '1:959517909012:web:5745dc44c5bd67088d8701',
    messagingSenderId: '959517909012',
    projectId: 'flora-d6444',
    authDomain: 'flora-d6444.firebaseapp.com',
    storageBucket: 'flora-d6444.firebasestorage.app',
    measurementId: 'G-7E2DEMGBP3',
  );
}
